name: Feature Request
description: Suggest an enhancement for ESE tools or processes
title: '[FEATURE] Brief description'
labels: ['enhancement', 'needs-discussion']

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request for ESE
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: Describe the current limitation or need...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions you've considered...
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Essential for ESE advancement
    validations:
      required: true 